name: webhook

on:
  workflow_call:
  pull_request:
    paths-ignore:
      - "README.md"
    branches:
      - main
  push:
    paths-ignore:
      - "README.md"
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions: write-all
  #permissions:
  #contents: read
  #id-token: write

concurrency:
  group: "content"
  cancel-in-progress: true

# Default to bash
defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Trigger Workflow
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.GHA_WORKFLOW_TRIGGER }}
        script: |
          github.rest.actions.createWorkflowDispatch({
            owner: "robinmordasiewicz",
            repo: "fortinet-hugo-template",
            workflow_id: 'content.yaml',
            ref: 'main',
          })
